'''List of annotation names.'''

DECLARED = 'declared'
DEFINED = 'defined'
ENUM = 'enum'
ERRCHECK = 'errcheck'
FORWARD_DECLARATION = 'forward-declaration'
METHOD = 'method'
MIXIN = 'mixin'
NAME = 'name'
ORIGINAL_NAME = 'original-name'
REQUIRED = 'required'
USE_VA_LIST_TAG = 'use-va-list-tag'
